name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Changelog
        run: echo "# Release Notes" > changelog.txt  # Replace this with your actual changelog content

      - name: Set release tag
        id: set_tag
        run: |
          tag=$(git rev-parse --short=8 ${{ github.sha }})
          echo "tag=${tag}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            changelog.txt
          body_path: changelog.txt
          tag_name: ${{ env.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install OpenSSL Development Packages
      run: sudo apt-get update && sudo apt-get install -y libssl-dev

    - name: Build and upload Linux artifacts
      id: upload_linux
      uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: rust-koditool-random_ep-linux-x86_64,rust-koditool-tvmode-linux-x86_64
        ref: ${{ env.set_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macOS-latest
    needs: create-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and upload macOS artifacts
      id: upload_macos
      uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: rust-koditool-random_ep-macos,rust-koditool-tvmode-macos
        ref: ${{ env.set_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    needs: create-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-msvc

    - name: Build and upload Windows artifacts
      id: upload_windows
      uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: rust-koditool-random_ep-windows-x86_64.exe,rust-koditool-tvmode-windows-x86_64.exe
        ref: ${{ env.set_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}



#  build-freebsd:
#    runs-on: ubuntu-latest
#    needs: create-release
#
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Install Rust
#      run: rustup update stable
#
#    - name: Install OpenSSL Development Packages
#      run: sudo apt-get update && sudo apt-get install -y libssl-dev
#
#    - name: Install cross-compilation tools
#      uses: taiki-e/setup-cross-toolchain-action@v1
#      with:
#        target: x86_64-unknown-freebsd
#    - run: cargo build --release
#    - run: cp target/x86_64-unknown-freebsd/release/kodi-random_ep ./rust-koditool-random_ep-freebsd-x86_64
#    - run: cp target/x86_64-unknown-freebsd/release/kodi-tvmode ./rust-koditool-tvmode-freebsd-x86_64
#
#    - name: Set release tag
#      id: set_tag
#      run: |
#        tag=$(git rev-parse --short=8 ${{ github.sha }})
#        echo "::set-output name=tag::${tag}"
#
#    - name: Get release ID
#      id: get_release_id
#      run: echo "::set-output name=id::$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.set_tag.outputs.tag }} | jq -r '.id')"
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#    - name: Upload binaries
#      uses: actions/upload-artifact@v2
#      with:
#        name: Binaries
#        path: |
#          rust-koditool-random_ep-freebsd-x86_64
#          rust-koditool-tvmode-freebsd-x86_64
#
#    - name: Attach binaries to release
#      id: attach_artifacts
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.create-release.outputs.release_id }}/assets?name=rust-koditool-freebsd-x86_64
#        asset_path: rust-koditool-freebsd-x86_64
#        asset_name: rust-koditool-freebsd-x86_64
#        asset_content_type: application/octet-stream
